spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/xxxx?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,wall
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    # 打开PSCache,并且制定每个PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    timeEvictionTimeMillis: 300000
    vaildationQuery: select 1 from dual
    testWhiledle: true
    testOnBorrow: false
    testOnReturn: false
    druid:
      username: feiyst
      password: druid1122
      logSlowSql: true

# redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5s
